client:
	gcc -o stockclient stockclient.c csapp.c -lpthread
	gcc -o multiclient multiclient.c csapp.c -lpthread
	gcc -o multiclient_test multiclient_test.c csapp.c -lpthread
	gcc -o echocli echocli.c csapp.c -lpthread
	gcc -o echoser echoser.c csapp.c -lpthread
	gcc -o debugclient -g stockclient.c csapp.c -lpthread
clean:
	rm *client