client:
	gcc -o stockclient stockclient.c csapp.c -lpthread
	gcc -o multiclient multiclient.c csapp.c -lpthread
	gcc -o multiclient_benchmark multiclient_benchmark.c csapp.c -lpthread
clean:
	rm *client multiclient_benchmark